import time
import pyautogui

time.sleep(3.4)

t= 0.2

loc1 = 320,564
loc2 = 356,564
loc3 = 392,564
loc4 = 426,564
loc5 = 462,564
loc6 = 500,564
loc7 = 536,564

#Move section for Geothermy
def click(loc,sleep):
    pyautogui.moveTo(loc)
    pyautogui.press("q")
    time.sleep(sleep)
pyautogui.moveTo(loc3)
pyautogui.press("q")
time.sleep(t*2)
pyautogui.moveTo(loc5)
pyautogui.press("q")
time.sleep(t*2)
pyautogui.moveTo(loc3)
pyautogui.press("q")
time.sleep(t*2)
pyautogui.moveTo(loc1)
pyautogui.press("q")
time.sleep(t*2)
pyautogui.moveTo(loc3)
pyautogui.press("q")
time.sleep(t*2)
pyautogui.moveTo(loc5)
pyautogui.press("q")
time.sleep(t*2)
pyautogui.moveTo(loc3)
pyautogui.press("q")
time.sleep(t*5)
pyautogui.moveTo(loc3)
pyautogui.press("q")
time.sleep(t*2)
pyautogui.moveTo(loc5)
pyautogui.press("q")
time.sleep(t*2)
pyautogui.moveTo(loc3)
pyautogui.press("q")
time.sleep(t*2)
pyautogui.moveTo(loc5)
pyautogui.press("q")
time.sleep(t*2)
pyautogui.moveTo(loc7)
pyautogui.press("q")
time.sleep(t-0.1)
pyautogui.moveTo(loc6)
pyautogui.press("q")
time.sleep(t-0.1)
pyautogui.moveTo(loc5)
pyautogui.press("q")
time.sleep(t-0.1)
pyautogui.moveTo(loc4)
pyautogui.press("q")
time.sleep(t-0.1)
pyautogui.moveTo(loc3)
pyautogui.press("q")
time.sleep(t-0.1)
pyautogui.moveTo(loc2)
pyautogui.press("q")
time.sleep(t*2)
pyautogui.moveTo(loc2)
pyautogui.press("q")
time.sleep(t*2)
pyautogui.moveTo(loc5)
pyautogui.press("q")
time.sleep(t*2)
pyautogui.moveTo(loc3)
pyautogui.press("q")
time.sleep(t*2)
pyautogui.moveTo(loc1)
pyautogui.press("q")
time.sleep(t*2)
pyautogui.moveTo(loc3)
pyautogui.press("q")
time.sleep(t*2)
pyautogui.moveTo(loc5)
pyautogui.press("q")
time.sleep(t*2)
pyautogui.moveTo(loc3)
pyautogui.press("q")
time.sleep(t*2+0.1)
pyautogui.moveTo(loc7)
pyautogui.press("q")
time.sleep(t*2)
pyautogui.moveTo(loc6)
pyautogui.press("q")
time.sleep(t)
pyautogui.moveTo(loc5)
pyautogui.press("q")
time.sleep(t*2)
pyautogui.moveTo(loc4)
pyautogui.press("q")
time.sleep(t-0.1)
pyautogui.moveTo(loc3)
pyautogui.press("q")
time.sleep(t*2)
pyautogui.moveTo(loc2)
pyautogui.press("q")
time.sleep(t*2)
pyautogui.moveTo(loc1)
pyautogui.press("q")
time.sleep(t)

